### ISSUE TITLE
Updating datasource leads to KeyError

### ISSUE THREAD

**Issue by mandarvaze** [pyeve/eve-sqlalchemy#197]
Original problem reported [here](https://github.com/pyeve/eve/issues/517) - was deferred in main eve, as it is sqlalchemy specific

Workaround mentioned [there](https://github.com/pyeve/eve/issues/517#issuecomment-64988153) and [here](https://github.com/pyeve/eve-sqlalchemy/issues/56#issuecomment-285877807) works. 

This could be trivially fixed via documentation. Just mention how to update `datasource`

details from main eve documentation do not work.

```
DOMAIN['goods'].update({
    'datasource': {
        'default_sort': [('id', -1)]
    }
  })
```

**does not work**

`DOMAIN['goods']['datasource']['default_sort'] = [('id', -1)]` 

works.

**Comment by dkellner** [comment]
I could not find the documentation/example you're referring to, maybe it was corrected already?

Due to how `update` works, this will always overwrite `DOMAIN['goods']['datasource']` with the supplied value, which in this case is a dictionary lacking required keys. I can see how this can be confusing, but it is not related to `datasource` in any way. Maybe a more general warning on using `update`  in https://eve-sqlalchemy.readthedocs.io/en/latest/tutorial.html#eve-settings would be appropriate. What do you think?

**Comment by mandarvaze** [comment]
I understand now.

I reason I (and others from existing "bug" reports, linked above) mentioned `datasource` is because most of us face this issue when "updating" `datasource`

General warning definitely would be useful - may in the example use `datasource`?
