### ISSUE TITLE
Is it possible to change compatible version of Eve from "<0.8" to the latest Eve?

### ISSUE THREAD

**Issue by vr-devs** [pyeve/eve-sqlalchemy#204]
Hi!
Is it possible to use eve_sqlalchemy with the latest Eve 1.1.4? (fork this project and change Eve version in setup.py)
What errors can this lead to? 
Thanks in advance!

**Comment by dkellner** [comment]
No, unfortunately not. The version pinning was introduced because there are already incompatibilities with Eve 0.8, that have to be addressed. The current Eve-SQLAlchemy will most likely not work at all with Eve >= 0.8.

If you want to give it a try, just run the tests for the latest Eve version and try to fix any errors you encounter. I'm happy to provide assistance if you have further questions.
